language: python
python:
  - "2.7"
before_install:
  - wget -O ta-lib-0.4.0-src.tar.gz http://sourceforge.net/projects/ta-lib/files/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz/download
  - tar xvzf ta-lib-0.4.0-src.tar.gz
  - pushd ta-lib; ./configure; make; sudo make install; popd
  - sudo apt-get install gfortran
install:
  - cat etc/requirements_dev.txt  | grep -v "^#" | grep -v "^$" | grep -v ipython | grep -v nose== | grep -v scipy | grep -v matplotlib | grep -v statsmodels | grep -v patsy | xargs pip install --use-mirrors
  - etc/ordered_pip.sh etc/requirements.txt
before_script:
  - "flake8 zipline tests"
script:
  - nosetests --exclude=^test_examples
